name: Export issues
on:
  issue_comment:
    types: [created, deleted]
jobs:
  deploy:
    name: Export issues to S3
    runs-on: ubuntu-latest
    steps:
    - name: Export issues
      uses: niteoweb/export-issues-action@v2
      with:
        repo: ${{ github.repository }}
        org: ${{ github.repository_owner }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        out: issues
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: issues
        path: "issues/*.md"
